### PR TITLE
(FM-7389) allow `puppet6` as value for BEAKER_PUPPET_COLLECTION

### PR DESCRIPTION
**Pull request by tphoney**

### CODE REVIEW

**Comment by tphoney** [comment]
@eimlav my attempt

**Comment by eimlav** [comment]
@tphoney I've tried your changes and it seems to run 100%. I'll request a merge if you are happy to go ahead.

**Review by DavidS — COMMENTED** [review]
This doesn't look horrible, but I don't have cycles today to actually run the code.

**Review by DavidS — APPROVED** [review]
:shipit:

**Pull request merged**
